# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js app to Azure Web App - app-advanced3-6
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          # Debug step to confirm build artifacts
          ls -la .next || echo ".next directory not found"
      # Include .next directory explicitly in zip file
      - name: Zip artifact for deployment
        run: |
          # Ensure .next directory is included (not excluded due to dot prefix)
          zip -r release.zip . -x "node_modules/*"
          # Add .next directory explicitly
          zip -r release.zip .next
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: Add startup script
        run: |
          echo "Creating startup script..."
          echo "#!/bin/bash" > startup.sh
          echo "cd \$HOME/site/wwwroot" >> startup.sh
          echo "npm run build" >> startup.sh
          echo "npm start" >> startup.sh
          chmod +x startup.sh
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-advanced3-6'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEB0E71F703B4BDF89A28979EEEF310A }}
